// config.js - Centralized configuration for flowchart-judge
// All configurable variables and sheet names

var CONFIG = {
  SubmissionIdColumnName: "Submission ID",
  SubmissionTimestampColumnName: "Submission Timestamp",
  SubmissionStatusColumnName: "Submission Status",
  StatusColumnName: "Status",
  CodeFileUrlColumnName: "Code File URL",
  ProblemNumberColumnName: "Problem Number",
  TimestampColumnName: "Timestamp",
  EmailAddressColumnName: "Email Address",
  UploadFlowchartColumnName: "Upload your Flowchart",
  VerdictColumnName: "Verdict",
  ModelUsedColumnName: "Model Used",
  PromptVersionColumnName: "Prompt Version",
  GenerationTimestampColumnName: "Generation Timestamp",
  InputTokensColumnName: "Input Tokens",
  OutputTokensColumnName: "Output Tokens",
  TotalTokensColumnName: "Total Tokens",
  ResponseTimeColumnName: "Response Time (ms)",
  SafetyRatingsColumnName: "Safety Ratings",
  FinishReasonColumnName: "Finish Reason",
  CitationMetadataColumnName: "Citation Metadata",
  ModelVersionColumnName: "Model Used",
  ResponseIdColumnName: "Response ID",
  ThoughtsTokenCountColumnName: "Thoughts Token Count",
  TextTokenCountColumnName: "Text Token Count",
  ImageTokenCountColumnName: "Image Token Count",
  ImageMimeTypeColumnName: "Image MIME Type",
  promptVersion: "Production - 1st Aug 2025",
  // Status constants
  NewEntryStatus: "NEW",
  GeminiDoneStatus: "GEMINI_DONE",
  JudgeSubmittedStatus: "JUDGE_SUBMITTED",
  VerdictReadyStatus: "VERDICT_READY",
  SubmissionStatus: "SUBMITTED",
  generatedCodesFolder: "GeneratedCodes",
  masterSheet: "Master",
  logEventSheet: "event-log",
  metaSheet: "Meta",
  geminiApiKeyProperty: "GEMINI_API_KEY", // Fixed to match your script property name
  domjudgeApiUrl: "https://judge.csbasics.in/api/v4",
  domjudgeContestId: "2",
  domjudgeTeamId: "5",
  domjudgeUser: "Student01",
  domjudgePass: "Ppassword@123",
  geminiModel: "gemini-2.5-pro",
  geminiTemperature: 0,
  CannotProcessStatus: "CANNOT_PROCESS",
  geminiEndpoint: "https://generativelanguage.googleapis.com/v1beta/models/",
  // For batch: use geminiEndpoint + geminiModel + ':batchGenerateContent?key=' + API_KEY
  geminiBatchThreshold: 5, // Use batch mode if requests >= this number
  logLevelDebug: 1,
  logLevelError: 2,
  loggingLevel: 2,
  // Logging configuration
  logDateHeader: "DATE",
  logLevelHeader: "LOG_LEVEL", 
  logMessageHeader: "MESSAGE",
  logDebugString: "DEBUG",
  logErrorString: "ERROR",
  // Gemini response defaults
  defaultFinishReason: "STOP",
  domjudgeAdminUser: "shanti",
  domjudgeAdminPass: "shanti@justuju.in",
  // DomJudge submission configuration
  domjudgeLanguageId: "python3",
  domjudgeSolutionFilename: "solution.py",
  domjudgeZipFilename: "solution.zip",
  generatedCodeFileExtension: ".py",
  masterSheetColumns: [
    "Timestamp",
    "Email Address",
    "Problem Number",
    "Upload your Flowchart",
    "Status",
    "Code File URL",
    "Model Used",
    "Prompt Version",
    "Generation Timestamp",
    "Submission ID",
    "Submission Timestamp",
    "Submission Status",
    "Verdict",
    "Processing Duration",
    "Input Tokens",
    "Output Tokens",
    "Total Tokens",
    "Response Time (ms)",
    "Safety Ratings",
    "Finish Reason",
    "Citation Metadata",
    "Model Version",
    "Response ID",
    "Thoughts Token Count",
    "Text Token Count",
    "Image Token Count"
  ],
  metaSheetColumns: ["Problem Code", "Problem ID"],
  domjudgeSubmissionColumns: ["Submission ID", "Problem ID", "Verdict"],
};

function getConfig() {
  return CONFIG;
}
